// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD96siTHf23B9g8aulIkiHQ5p9MBgzOLI',
    appId: '1:947901140367:web:95cc3c3c2df8bf5ec38ffa',
    messagingSenderId: '947901140367',
    projectId: 'homeworks-6924d',
    authDomain: 'homeworks-6924d.firebaseapp.com',
    storageBucket: 'homeworks-6924d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG_nJ5XK7YFFGQ-fBJCvJJ0gD4h6bH6e4',
    appId: '1:947901140367:android:6e9ca77e4e126f52c38ffa',
    messagingSenderId: '947901140367',
    projectId: 'homeworks-6924d',
    storageBucket: 'homeworks-6924d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB68Rxct5usi64Is4dHzhsqCAT-bCP718E',
    appId: '1:947901140367:ios:47c9b7faced097a0c38ffa',
    messagingSenderId: '947901140367',
    projectId: 'homeworks-6924d',
    storageBucket: 'homeworks-6924d.appspot.com',
    iosClientId: '947901140367-fed3mijrjq3g34b5qgbbpb8jhepihegs.apps.googleusercontent.com',
    iosBundleId: 'com.example.scoolHomeWorking',
  );
}
