class EnTranslations {
  static Map<String, String> get map => {
        'newTask_buttonAdd': 'Add',
        'newTask_title': 'New task',
        'newTask_textFieldSubject': 'Subject...',
        'newTask_textFieldTask': 'Task...',
        'newTask_date': 'Task for',
        'newTask_ImportantTask': 'Important task:',
        'newTask_Remind': 'Remind',
        'newTask_Warning':
            'If the reminder is enabled, then after clicking on the "Add" button, an advertisement will be played, after which your task will be added.',
        'notification_TitleError': 'Error',
        'notification_TitleNotification': 'Notification',
        'colorPicker_Title': 'Subject color:',
        'colorPicker_ButtonApply': 'Apply',
        'systemNotification_Remind':
            'Reminder of the task in the subject of the',
        'newTask_notificationTaskAdded': 'Task added!',
        'newTask_notificationPastTime':
            'The assignment must be in the future tense!',
        'newTask_taskEmpty': 'You didn\'t write the assignment!',
        'newTask_subjectEmpty': 'You did not write the name of the subject!',
        'newTask_Donations': 'Donations to developer',
        'newTask_timeAt': 'at',
        'newTask_datePicker_helpText': 'Pick a date',
        'newTask_datePicker_cancelText': 'Cancel',
        'newTask_datePicker_confirmText': 'Confirm',
        'newTask_datePicker_fieldLabelText': 'Write the date',
        'newTask_datePicker_fieldHintText': 'MM/DD/YYYY',
        'newTask_timePicker_helpText': 'Pick a time',
        'newTask_timePicker_minuteLabelText': 'Minutes',
        'newTask_timePicker_hourLabelText': 'Hours',
        'taskList_NoHomeworks': 'No homeworks for this day',
        'taskList_Title': 'Tasks for',
        'taskList_ButtonDeleteTask': 'Delete task(s)',
        'taskList_ButtonChangeTask': 'Change task',
        'taskList_ImportantTask': 'IMPORTANT TASK',
        'Algebra': 'Algebra',
        'Astronomy': 'Astronomy',
        'Biology': 'Biology',
        'Geography': 'Geography',
        'Geometry': 'Geometry',
        'NaturalSciences': 'Natural sciences',
        'Drawing': 'Drawing',
        'ForeignLanguage': 'Foreign language',
        'Informatics': 'Informatics',
        'History': 'History',
        'LocalHistory': 'Local history',
        'Literature': 'Literature',
        'Maths': 'Maths',
        'WorldArt': 'World art',
        'Music': 'Music',
        'BasicMilitaryTraining': 'Basic military training',
        'SociallyUsefulWork': 'Socially useful work',
        'SocialScience': 'Social science',
        'World': 'World',
        'LifeSafetyFundamentals': 'Life Safety Fundamentals',
        'FundamentalsOfFinancialLiteracy': 'Fundamentals of financial literacy',
        'FundamentalsOfEconomics': 'Fundamentals of economics',
        'Design': 'Design',
        'Psychotraining': 'Psychotraining',
        'Rhetoric': 'Rhetoric',
        'NativeLiterature': 'Native literature',
        'NativeLanguage': 'Native language',
        'RussianLanguage': 'Russian language',
        'EnglishLanguage': 'English language',
        'Statistics': 'Statistics',
        'Technology': 'Technology',
        'Physics': 'Physics',
        'PhysicalTraining': 'Physical training',
        'Philosophy': 'Philosophy',
        'Chemistry': 'Chemistry',
        'Painting': 'Painting',
        'Ecology': 'Ecology',
        'newUpdate_buttonInstall': 'Install',
        'newUpdate_textInstalling': 'Installing...',
        'newUpdate_textUpdateIsAvailable': 'New update available!',
        'newUpdate_Title': 'New update',
      };
}
