class EnTranslations {
  static Map<String, String> get map => {
        'newTask_buttonAdd': 'Add',
        'newTask_title': 'New task',
        'editTask_title': 'Edit task',
        'newTask_textFieldSubject': 'Subject...',
        'newTask_textFieldTask': 'Task...',
        'newTask_date': 'Task for',
        'newTask_ImportantTask': 'Important task:',
        'newTask_Remind': 'Remind',
        'newTask_Warning':
            'If the reminder is enabled, then after clicking on the "Add" button, an advertisement will be played, after which your task will be added.',
        'notification_TitleError': 'Error',
        'notification_TitleCongratulations': 'Congratulations!',
        'notification_TitleNotification': 'Notification',
        'colorPicker_Title': 'Subject color:',
        'colorPicker_ButtonApply': 'Apply',
        'systemNotification_Remind':
            'Reminder of the task in the subject of the',
        'systemNotification_RemindAboutSubscriptionEnd':
            'Your subscription will end in 24 hours.',
        'newTask_notificationTaskAdded': 'Task added!',
        'newTask_notificationTaskChanged': 'Task edited!',
        'newTask_notificationTaskCreatedAgain':
            'The task has been successfully created again!',
        'newTask_notificationPastTime':
            'The assignment must be in the future tense!',
        'newTask_taskEmpty': 'You didn\'t write the assignment!',
        'newTask_subjectEmpty': 'You did not write the name of the subject!',
        'newTask_timeAt': 'at',
        'newTask_remainingTasks': 'Remaining',
        'newTask_notConnectedHomeworksProWarning':
            'As you do not have Homeworks Pro connected, you can only add 5 tasks and 3 reminders per date.',
        'taskList_NoHomeworks': 'No homeworks for this day',
        'taskList_Title': 'Tasks for',
        'taskList_ButtonDeleteTask': 'Delete',
        'taskList_ButtonChangeTask': 'Edit',
        'taskList_ImportantTask': 'IMPORTANT TASK',
        'Algebra': 'Algebra',
        'Astronomy': 'Astronomy',
        'Biology': 'Biology',
        'Geography': 'Geography',
        'Geometry': 'Geometry',
        'NaturalSciences': 'Natural sciences',
        'Drawing': 'Drawing',
        'ForeignLanguage': 'Foreign language',
        'Informatics': 'Informatics',
        'History': 'History',
        'LocalHistory': 'Local history',
        'Literature': 'Literature',
        'Maths': 'Maths',
        'WorldArt': 'World art',
        'Music': 'Music',
        'BasicMilitaryTraining': 'Basic military training',
        'SociallyUsefulWork': 'Socially useful work',
        'SocialScience': 'Social science',
        'World': 'World',
        'LifeSafetyFundamentals': 'Life Safety Fundamentals',
        'FundamentalsOfFinancialLiteracy': 'Fundamentals of financial literacy',
        'FundamentalsOfEconomics': 'Fundamentals of economics',
        'Design': 'Design',
        'Psychotraining': 'Psychotraining',
        'Rhetoric': 'Rhetoric',
        'NativeLiterature': 'Native literature',
        'NativeLanguage': 'Native language',
        'RussianLanguage': 'Russian language',
        'EnglishLanguage': 'English language',
        'Statistics': 'Statistics',
        'Technology': 'Technology',
        'Physics': 'Physics',
        'PhysicalTraining': 'Physical training',
        'Philosophy': 'Philosophy',
        'Chemistry': 'Chemistry',
        'Painting': 'Painting',
        'Ecology': 'Ecology',
        'newUpdate_buttonInstall': 'Install',
        'newUpdate_textInstalling': 'Installing...',
        'newUpdate_textUpdateIsAvailable': 'New update available!',
        'newUpdate_Title': 'New update',
        'proOverview_noAdTitle': 'No ads',
        'proOverview_noAdSubtitle': 'No more ads - just your content!',
        'proOverview_infinityTasksTitle': 'An unlimited number of tasks',
        'proOverview_infinityTasksSubtitle': 'Add as many tasks as you want!',
        'proOverview_infinityNotificationsTitle': 'Unlimited reminders',
        'proOverview_checkPayment': 'Checking payment...',
        'proOverview_alreadyProApp':
            'You have already connected Homeworks Pro!',
        'proOverview_checkPaymentSberbank':
            'You should receive a push notification from Sberbank to confirm payment. If not, please go to the Sberbank app or website and check the confirmation in the notifications.',
        'proOverview_infinityNotificationsSubtitle':
            'Create unlimited reminders!',
        'proOverview_newFeauteresTitle': 'New features',
        'proOverview_newFeauteresSubtitle':
            'You will be one of the first to test new features!',
        'proOverview_month': 'month',
        'proOverview_year': 'year',
        'proOverview_buttonConnect': 'Connect',
        'proOverview_userAgreementWarn': 'By connecting, you agree to the',
        'proOverview_userAgreement': 'User Agreement',
        'proOverview_userAgreementTitle': 'User Agreement',
        'proOverview_homeworksProConnected':
            'You have successfully connected Homeworks Pro!',
        'proOverview_notificationErrorCanceled':
            'The purchase could not be completed. Please try again later. {cancelled}',
        'proOverview_profitablePrice': 'Profitable',
        'taskDetail_title': 'Reminder',
        'profile_title': 'Your profile',
        'profile_accountTitle': 'Account',
        'profile_subscriptionTitle': 'Subscription',
        'profile_subscriptionActiveUntil': 'active until',
        'profile_subscriptionNotActive': 'inactive',
        'profile_logout': 'Sign out',
        'profile_notLogged': 'You are not authorized!',
        'profile_login': 'Login',
        'login_userNotFound': 'No user found with this email address!',
        'login_wrongPassword': 'Wrong password!',
        'login_weakPassword': 'Weak password!',
        'login_emailAlreadyInUse': 'Email already in use!',
        'login_loadingPleaseWait': 'Please, wait...',
        'login_buttonRegister': 'Register',
        'login_buttonLogin': 'Login',
        'login_alreadyHaveAnAccount': 'Already have an account?',
        'login_noAccount': 'Don\'t have an account?',
        'login_titleAuthorization': 'Authorization',
        'login_textInputEmailAddress': 'Email...',
        'login_textInputPassword': 'Password...',
        'login_textWarning':
            'Payment receipts will be sent to this email address.',
        'payment_subtitle': 'Pro app version',
        'payment_description': 'Payment order on',
      };
}
