class RuTranslations {
  static Map<String, String> get map => {
        'newTask_buttonAdd': 'Добавить',
        'newTask_title': 'Новое задание',
        'editTask_title': 'Изменить задание',
        'newTask_textFieldSubject': 'Предмет...',
        'newTask_textFieldTask': 'Задание...',
        'newTask_date': 'Задание на',
        'newTask_ImportantTask': 'Важное задание:',
        'newTask_Remind': 'Напомнить',
        'newTask_Warning':
            'Если включено напоминание, то после нажатия на кнопку «Добавить» воспроизведётся реклама, после чего Ваше задание будет добавлено.',
        'notification_TitleError': 'Ошибка',
        'notification_TitleCongratulations': 'Поздравляем!',
        'notification_TitleNotification': 'Уведомление',
        'colorPicker_Title': 'Цвет предмета:',
        'colorPicker_ButtonApply': 'Применить',
        'systemNotification_Remind': 'Напоминание о задании по предмету',
        'systemNotification_RemindAboutSubscriptionEnd':
            'Ваша подписка закончится через 24 часа.',
        'newTask_notificationTaskAdded': 'Задание добавлено!',
        'newTask_notificationTaskChanged': 'Задание изменено!',
        'newTask_notificationTaskCreatedAgain':
            'Задание успешно создано ещё раз!',
        'newTask_notificationPastTime':
            'Задание должно быть в будущем времени!',
        'newTask_taskEmpty': 'Вы не вписали задание!',
        'newTask_subjectEmpty': 'Вы не вписали название предмета!',
        'newTask_timeAt': 'в',
        'newTask_remainingTasks': 'Осталось',
        'newTask_notConnectedHomeworksProWarning':
            'Поскольку у Вас не подключен Homeworks Pro, Вы можете добавить только 5 заданий и 3 напоминания на одну дату.',
        'taskList_NoHomeworks': 'На этот день нет домашних заданий',
        'taskList_Title': 'Задания на',
        'taskList_ButtonDeleteTask': 'Удалить',
        'taskList_ButtonChangeTask': 'Изменить',
        'taskList_ImportantTask': 'ВАЖНОЕ ЗАДАНИЕ',
        'Algebra': 'Алгебра',
        'Astronomy': 'Астрономия',
        'Biology': 'Биология',
        'Geography': 'География',
        'Geometry': 'Геометрия',
        'NaturalSciences': 'Естествознание',
        'Drawing': 'ИЗО',
        'ForeignLanguage': 'Иностранный язык',
        'Informatics': 'Информатика',
        'History': 'История',
        'LocalHistory': 'Краеведение',
        'Literature': 'Литература',
        'Maths': 'Математика',
        'WorldArt': 'МХК',
        'Music': 'Музыка',
        'BasicMilitaryTraining': 'Начальная военная подготовка',
        'SociallyUsefulWork': 'Общественно-полезный труд',
        'SocialScience': 'Обществознание',
        'World': 'Окружающий мир',
        'LifeSafetyFundamentals': 'ОБЖ',
        'FundamentalsOfFinancialLiteracy': 'Основы финансовой грамотности',
        'FundamentalsOfEconomics': 'Основы экономики',
        'Design': 'Проектирование',
        'Psychotraining': 'Психотренинг',
        'Rhetoric': 'Риторика',
        'NativeLiterature': 'Родная литература',
        'NativeLanguage': 'Родной язык',
        'RussianLanguage': 'Русский язык',
        'EnglishLanguage': 'Английский язык',
        'Statistics': 'Статистика',
        'Technology': 'Технология',
        'Physics': 'Физика',
        'PhysicalTraining': 'Физкультура',
        'Philosophy': 'Философия',
        'Chemistry': 'Химия',
        'Painting': 'Черчение',
        'Ecology': 'Экология',
        'newUpdate_buttonInstall': 'Установить',
        'newUpdate_textInstalling': 'Установка...',
        'newUpdate_textUpdateIsAvailable': 'Доступно новое обновление!',
        'newUpdate_Title': 'Новое обновление',
        'proOverview_noAdTitle': 'Нет рекламы',
        'proOverview_noAdSubtitle':
            'Больше никакой рекламы - только ваш контент!',
        'proOverview_infinityTasksTitle': 'Неограниченное количество задач',
        'proOverview_infinityTasksSubtitle':
            'Добавляйте столько задач, сколько нужно!',
        'proOverview_infinityNotificationsTitle':
            'Неограниченное количество напоминаний',
        'proOverview_infinityNotificationsSubtitle':
            'Создавайте неограниченное количество напоминаний!',
        'proOverview_newFeauteresTitle': 'Новые функции',
        'proOverview_newFeauteresSubtitle':
            'Вы будете одним из первых, кто протестирует новые функции!',
        'proOverview_month': 'месяц',
        'proOverview_year': 'год',
        'proOverview_buttonConnect': 'Подключить',
        'proOverview_checkPayment': 'Проверка оплаты...',
        'proOverview_alreadyProApp': 'Вы уже подключили Homeworks Pro!',
        'proOverview_checkPaymentSberbank':
            'Вы должны получить push-уведомление от Сбербанка для подтверждения платежа. Если этого не произошло, зайдите в приложение или на сайт Сбербанка и проверьте подтверждение в уведомлениях.',
        'proOverview_userAgreementWarn': 'Подключаясь, Вы соглашаетесь с',
        'proOverview_userAgreement': 'Пользовательским Соглашением',
        'proOverview_userAgreementTitle': 'Пользовательское Соглашение',
        'proOverview_homeworksProConnected':
            'Вы успешно подключили Homeworks Pro!',
        'proOverview_notificationErrorCanceled':
            'Не удалось завершить покупку. Пожалуйста, повторите попытку позже. {cancelled}',
        'proOverview_profitablePrice': 'Выгодно',
        'taskDetail_title': 'Напоминание',
        'profile_title': 'Ваш профиль',
        'profile_accountTitle': 'Аккаунт',
        'profile_subscriptionTitle': 'Подписка',
        'profile_subscriptionActiveUntil': 'активна до',
        'profile_subscriptionNotActive': 'неактивна',
        'profile_logout': 'Выйти из аккаунта',
        'profile_notLogged': 'Вы не вошли в аккаунт!',
        'profile_login': 'Войти',
        'login_userNotFound':
            'Пользователь с таким адресом электронной почты не найден!',
        'login_wrongPassword': 'Неверный пароль!',
        'login_weakPassword': 'Пароль слишком короткий',
        'login_emailAlreadyInUse':
            'Этот адрес электронной почты уже существует!',
        'login_loadingPleaseWait': 'Пожалуйста, подождите...',
        'login_buttonRegister': 'Зарегистрироваться',
        'login_buttonLogin': 'Войти',
        'login_alreadyHaveAnAccount': 'Уже есть аккаунт?',
        'login_noAccount': 'Нет аккаунта?',
        'login_titleAuthorization': 'Авторизация',
        'login_textInputEmailAddress': 'Почта...',
        'login_textInputPassword': 'Пароль...',
        'login_textWarning':
            'Квитанции об оплате будут отправлены на этот адрес электронной почты.',
        'payment_subtitle': 'Pro версия приложения',
        'payment_description': 'Оплата заказа для',
      };
}
