class RuTranslations {
  static Map<String, String> get map => {
        'newTask_buttonAdd': 'Добавить',
        'newTask_title': 'Новое задание',
        'editTask_title': 'Изменить задание',
        'newTask_textFieldSubject': 'Предмет...',
        'newTask_textFieldTask': 'Задание...',
        'newTask_date': 'Задание на',
        'newTask_ImportantTask': 'Важное задание:',
        'newTask_Remind': 'Напомнить',
        'newTask_Warning':
            'Если включено напоминание, то после нажатия на кнопку «Добавить» воспроизведётся реклама, после чего Ваше задание будет добавлено.',
        'notification_TitleError': 'Ошибка',
        'notification_TitleNotification': 'Уведомление',
        'colorPicker_Title': 'Цвет предмета:',
        'colorPicker_ButtonApply': 'Применить',
        'systemNotification_Remind': 'Напоминание о задании по предмету',
        'newTask_notificationTaskAdded': 'Задание добавлено!',
        'newTask_notificationTaskChanged': 'Задание изменено!',
        'newTask_notificationPastTime':
            'Задание должно быть в будущем времени!',
        'newTask_taskEmpty': 'Вы не вписали задание!',
        'newTask_subjectEmpty': 'Вы не вписали название предмета!',
        'newTask_timeAt': 'в',
        'newTask_datePicker_helpText': 'Выберите дату',
        'newTask_datePicker_cancelText': 'Отмена',
        'newTask_datePicker_confirmText': 'Выбрать',
        'newTask_datePicker_fieldLabelText': 'Напишите дату',
        'newTask_datePicker_fieldHintText': 'ММ/ДД/ГГГГ',
        'newTask_timePicker_helpText': 'Выберите время',
        'newTask_timePicker_minuteLabelText': 'Минуты',
        'newTask_timePicker_hourLabelText': 'Часы',
        'newTask_remainingTasks': 'Осталось',
        'newTask_lastZeroTasks':
            'Поскольку у Вас не подключена Pro-версия приложения, Вы можете записывать только 5 задач на одну дату.',
        'newTask_lastZeroNotifications':
            'Поскольку у вас не подключена Pro-версия приложения, вы можете установить уведомления только для 3-х задач.',
        'taskList_NoHomeworks': 'На этот день нет домашних заданий',
        'taskList_Title': 'Задания на',
        'taskList_ButtonDeleteTask': 'Удалить',
        'taskList_ButtonChangeTask': 'Изменить',
        'taskList_ImportantTask': 'ВАЖНОЕ ЗАДАНИЕ',
        'Algebra': 'Алгебра',
        'Astronomy': 'Астрономия',
        'Biology': 'Биология',
        'Geography': 'География',
        'Geometry': 'Геометрия',
        'NaturalSciences': 'Естествознание',
        'Drawing': 'ИЗО',
        'ForeignLanguage': 'Иностранный язык',
        'Informatics': 'Информатика',
        'History': 'История',
        'LocalHistory': 'Краеведение',
        'Literature': 'Литература',
        'Maths': 'Математика',
        'WorldArt': 'МХК',
        'Music': 'Музыка',
        'BasicMilitaryTraining': 'Начальная военная подготовка',
        'SociallyUsefulWork': 'Общественно-полезный труд',
        'SocialScience': 'Обществознание',
        'World': 'Окружающий мир',
        'LifeSafetyFundamentals': 'ОБЖ',
        'FundamentalsOfFinancialLiteracy': 'Основы финансовой грамотности',
        'FundamentalsOfEconomics': 'Основы экономики',
        'Design': 'Проектирование',
        'Psychotraining': 'Психотренинг',
        'Rhetoric': 'Риторика',
        'NativeLiterature': 'Родная литература',
        'NativeLanguage': 'Родной язык',
        'RussianLanguage': 'Русский язык',
        'EnglishLanguage': 'Английский язык',
        'Statistics': 'Статистика',
        'Technology': 'Технология',
        'Physics': 'Физика',
        'PhysicalTraining': 'Физкультура',
        'Philosophy': 'Философия',
        'Chemistry': 'Химия',
        'Painting': 'Черчение',
        'Ecology': 'Экология',
        'newUpdate_buttonInstall': 'Установить',
        'newUpdate_textInstalling': 'Установка...',
        'newUpdate_textUpdateIsAvailable': 'Доступно новое обновление!',
        'newUpdate_Title': 'Новое обновление',
        'proOverview_noAdTitle': 'Нет рекламы',
        'proOverview_noAdSubtitle':
            'Больше никакой рекламы - только ваш контент!',
        'proOverview_infinityTasksTitle': 'Неограниченное количество задач',
        'proOverview_infinityTasksSubtitle':
            'Добавляйте столько задач, сколько нужно!',
        'proOverview_infinityNotificationsTitle':
            'Неограниченное количество напоминаний',
        'proOverview_infinityNotificationsSubtitle':
            'Создавайте неограниченное количество напоминаний!',
        'proOverview_month': 'месяц',
        'proOverview_buttonConnect': 'Подключить',
        'proOverview_userAgreementWarn': 'Подключаясь, Вы соглашаетесь с',
        'proOverview_userAgreement': 'Пользовательским Соглашением',
        'proOverview_userAgreementTitle': 'Пользовательское Соглашение',
      };
}
